### ISSUE TITLE
Fix repair sometimes not fixing wheels.

### ISSUE THREAD

**Issue by DanielVF** [OFPSDEV/BECTI#109]
Sometimes when a vehicle's wheels are damaged, you can't fix it with a repair kit. The received wisdom from players is to shoot up the vehicle with grenades/tank rounds to damage it more, then repair. This  turns out poorly for everyone involved.

The problem is that a vehicle may have no overall damage, but still have individually damaged components/hitpoints/sections. To fix this, we need to repair each component/hitpoint/section individually after the main repair is complete.

References:

- https://community.bistudio.com/wiki/getHitPointDamage
- https://community.bistudio.com/wiki/setHitPointDamage
- https://community.bistudio.com/wiki/getHit
- https://community.bistudio.com/wiki/setHit
- https://github.com/OFPSDEV/BECTI/blob/754f71f5ff3ae3224710b45837730e9ce20c5173/becti_zerty_SS.Altis/addons/strat_mode/Functions/SM_RepairVehicule.sqf

**Comment by SpanishSurfer** [comment]
This was fixed right?

**Comment by thecoolestname36** [comment]
I wrote some code that was commented out. It gets the wheels on the vehicle being repaired but does not work. I just wanted to write it down for notes for other people.

d3b9cc2

**Comment by thecoolestname36** [comment]
Redundant, look for 'Repair Script'
