### ISSUE TITLE
Implement game changes to reduce use of MBT

### ISSUE THREAD

**Issue by OFPSDEV** [OFPSDEV/BECTI#112]
*1 Raising MBT prices to $25k-$30k depending on the MBT.  
*Don't forget the INDY tank.
*Remove possibility for KUMA to spawn in all towns EXCEPT 500 towns.
*Edit 500 towns so odds of KUMA spawning are VERY LOW.

**Comment by SpanishSurfer** [comment]
https://github.com/OFPSDEV/BECTI/commit/ddaf3049303fd5c0e68d5bff07c1988f8f1270d6
