### ISSUE TITLE
Ear Plugs Script

### ISSUE THREAD

**Issue by SpanishSurfer** [OFPSDEV/BECTI#113]
Got this request from some of the admins, what do you all think?

Hello,

Other day i play sandbox wasteland game and they have a script build in there mission that called earplug
What it does it reduce the noise of the vehicles so you can better hear the people talking in the game.

Can you guys put this scrip on the missions, it will be awesome to have it.

here are a few links where you can find the scripts.

http://www.armaholic.com/page.php?id=26624
http://blackwing.co.uk/forum/m/15692364 ... nd-in-heli

I hope this help

regards
Bel

http://ofps.net/viewtopic.php?f=6&t=310

**Comment by thecoolestname36** [comment]
Nice, the one that I was looking at required some agm mod to be implemented as well.  This looks nice and easy.

**Comment by SpanishSurfer** [comment]
Only problem now with the script is that it doesn't pop up after dying...

ideas?

**Comment by SpanishSurfer** [comment]
:33 PM - Sari: just had a thought, that earplugs thing is an addaction right?
2:34 PM - SpanishSurfer: [player] execVM "addons\ear_plugs\simpleEP.sqf";
2:45 PM - Sari is now Online.
2:46 PM - Sari: ok simple way to do it would be to stick one copy of that in init_client and another in cl > fnc  > client_onplayerkilled
2:49 PM - Sari: though frankly it would be neater to add 2 actions (put on and take off) in cl >fnc  >addmissionactions
2:50 PM - SpanishSurfer: hmm ok
2:51 PM - Sari: in the earplugs script the addeventhandler is redundant because the mission removes all eventhandles on respawn

**Comment by SpanishSurfer** [comment]
You've been on a role, knock this out of park and be a hero for players on the server.

**Comment by SpanishSurfer** [comment]
Lets see what you got outlawled!

**Comment by zerty** [comment]
-put  in the /Client/functions/Client_AddMissionActions.sqf file;
"""
[player] execVM "addons\ear_plugs\simpleEP.sqf";
1 fadeSound 1;
"""


- in the "addons\ear_plugs\simpleEP.sqf" remove the last part:
"""
_u addEventHandler ["Respawn",{
	1 fadeSound 1;
	(_this select 0) addAction _p;
}];
"""

And don't forget to add to add proper credits in the map menu.

**Comment by SpanishSurfer** [comment]
Thanks Zerty

**Comment by thecoolestname36** [comment]
See commit for comments.

1b1d85fa4ebf0606eaa5019dcb7597fe9e0fb568

As for the map credits... No comments at all, don't know where this was from.

**Comment by thecoolestname36** [comment]
Fkdmt, Forgot about resetting the audio on AddAction 

cf3ba5e4e698c65f36d1a6584f8a5d201b26a5fa

**Comment by zerty** [comment]
/addons/strat_mode/Functions/SM_DrawHelp.sqf Credit section , there are some stuff missing inside

**Comment by thecoolestname36** [comment]
Zerty, I dont know who to credit.  I didnt download it and there were absolutely NO comments on the files...

**Comment by zerty** [comment]
http://www.armaholic.com/page.php?id=26624 

"Simple Earplugs

by
654wak654"

**Comment by thecoolestname36** [comment]
Credit: 48d17459ad36edac30c368dc3b768c0762b04964
