### ISSUE TITLE
New Upgrade TIER HF3

### ISSUE THREAD

**Issue by SpanishSurfer** [OFPSDEV/BECTI#117]
HF3 = heavy artillery for both sides.

COST TO UPGRADE = $100,000

I'm not 100% familiar with the upgrade tiers and don't want to fudge it up. Mind putting this in?

**Comment by thecoolestname36** [comment]
I really wana make both uavs at air tier 2.  It would give the AA jet some purpose early on.

**Comment by thecoolestname36** [comment]
Also good counter to only tanks.  Since tanks are tier two, it would only make sense.

**Comment by thecoolestname36** [comment]
f23a115ceaec8cbbe93bad72675c4ef9dec01d00

Done

**Comment by SpanishSurfer** [comment]
Coolest the 3rd heavy factory tier does not show or allow commanders to upgrade :(

**Comment by MarkusNemesis** [comment]
Line 31 of BECTI/becti_zerty_SS.Altis/common/config/Upgrades/Upgrades_West.sqf

Needs to read:
_lev=_lev+	[3];
