### ISSUE TITLE
Repair Script

### ISSUE THREAD

**Issue by SpanishSurfer** [OFPSDEV/BECTI#118]
Needs some love, needs to work when wheels are lost.

**Comment by SpanishSurfer** [comment]
I think this was fixed

**Comment by thecoolestname36** [comment]
I wrote some code that was commented out.  It gets the wheels on the vehicle being repaired but does not work.  I just wanted to write it down for notes for other people.

**Comment by DanielVF** [comment]
Having recently tested fixing many broken wheels in-game, this does still need work. Thecoolest's code looks to be on the right track.

**Comment by thecoolestname36** [comment]
Closed redundant issue "https://github.com/OFPSDEV/BECTI/issues/109".

**Comment by SpanishSurfer** [comment]
Shot out all the tires on the MRAP and still couldn't get the repair function to pop up to fix them.

**Comment by thecoolestname36** [comment]
Yeah, spanish. That code is commented out. i thew it in there so people could add input if they had some.  Its not different at all.
