### ISSUE TITLE
Military Installation, base area bugs

### ISSUE THREAD

**Issue by SpanishSurfer** [OFPSDEV/BECTI#119]
Sometimes commanders are unable to put any more buildings after placing a Military installation. This has been happening quite a bit on the Guerrilla mission.  It says something like "The xxx needs a military installation to be created" which tells me it's not registering the base area.

I believe it may have something to do with elevation but I'm not sure.... Ideas?

**Comment by thecoolestname36** [comment]
Are you sure this problem exists in the main mission file.  I remember I merged my commander cam the same time that you were creating the gurella mode.  I think maybe the code wasn't transferred correctly.

**Comment by SpanishSurfer** [comment]
Confirmed on normal BECTI, it doesn't like hills

**Comment by MarkusNemesis** [comment]
make sure the code is using the correct getpos, as getpos, getposASL and
getposATL all work differently. So, the code that checks the military
installation's proximity needs to use the same function for getting
positions and finding distances, etc.

**Comment by thecoolestname36** [comment]
Kk ill take a look into this once i get a chance.

**Comment by thecoolestname36** [comment]
ad929902fd969a3b4e3971bb35e7696e1aa811f6

Should be done

**Comment by SpanishSurfer** [comment]
Cool, way too many changes on here that have nothing to do with base construction.  Please only upload a base construction fix.  You've got edits on here on adaptive group size, which was painstakingly worked on for the server.  Your town activation near bases is also there, which I'm not sold on.  You have a ton of edits on here with multiple things....just one issue at a time please.

**Comment by thecoolestname36** [comment]
These things are all disabled and assigned a parameter so it will have no effect. Adaptive groupsize was explicitly stated as 12 inside of its .sqf file and overriding its respective parameter, this is a fix.  The base construction bug fix is completed in the function 'Client_ConstructionCam_PlacingBuilding.sqf'

**Comment by thecoolestname36** [comment]
65723abdec6ff637919f4f8f8ae1bee022553050
