### ISSUE TITLE
Slow down Town Captures

### ISSUE THREAD

**Issue by SpanishSurfer** [OFPSDEV/BECTI#120]
I need to slow down the speed at which towns are capped when it's "all clear." It should take minutes and not seconds, the fast rate is causing issues.

**Comment by DanielVF** [comment]
With this change Bluefor/Opfor town occupation forces should
affect town captures in the same way that resistance forces do. This should stop fast capping.

I've only been able to test this change with me vs the resistance, not
bluefor on opfor. It needs that testing.

**Comment by SpanishSurfer** [comment]
How do you think this will this work if a player is in the shaded area and
defending a town that his team owns?  Will he be able to prevent a whole
team from capping the flag or just slow it down?  If its the latter then
that's exactly what we need.

**Comment by DanielVF** [comment]
A player outside the flag zone, or either team, won't affect it at all. We could make it so that players work like town occupation if you wanted.

**Comment by SpanishSurfer** [comment]
If players have no effect we'll leave it that way to prevent a player from
hiding in a building and making gameplay painful, good job man can't wait
to test.
