### ISSUE TITLE
Revert Repair Function back to Vanilla

### ISSUE THREAD

**Issue by SpanishSurfer** [OFPSDEV/BECTI#126]
*Repair specialist type available for players
*No more full repairs with a toolkit (more realistic)
*Always works

**Comment by thecoolestname36** [comment]
I have the fix close to being implemented for zerty's:  d3b9cc2480ac8abda2b57641854230079099c829

If youre going with the vanilla, dont forget to close this ticket:  https://github.com/OFPSDEV/BECTI/issues/118

**Comment by SpanishSurfer** [comment]
Well if you're close we can leave it and I'll let you work.  Any way we can slow down repairs by 50%?
