### ISSUE TITLE
Birds Eye view base construction (commander only)

### ISSUE THREAD

**Issue by OFPSDEV** [OFPSDEV/BECTI#7]
With ZEUS available I don't see why we can't have a birds eye view construction menu just like in Arma 2 available to the commander.  Give him a 500m range from the MHQ to allow him to pan around in birds eye view and build his bases.  Players who are not the Commander would not be allowed to go into this view mode.

**Comment by thecoolestname36** [comment]
f8b4df78ee8c937b389fa47fdda8ccd6140de159

**Comment by thecoolestname36** [comment]
Commit-aholic.  Its done now.

86f37068caa8b1708ee368cc1d050b3242da75cf
f61779109f8f2a6526b4c46158311017c3e470ad
2ef313b72233aa99adf67c6a0000264795e5956d
10e976688080458b2ca9af2652320b277c98f8cb
ab8dac5822bafed90f50121935b2457d9da6763f

**Comment by SpanishSurfer** [comment]
Just played with this, everything looks good!

How do I zoom up/down and turn the camera left/right?

We may want to have a small reminder of what keys do what on the bottom left of the "Birds eye view"

**Comment by SpanishSurfer** [comment]
Found a bug, I can't access the build menu from a repair factory.

**Comment by thecoolestname36** [comment]
That small render idea is really good.  I might have to add it.  I was also wondering it it would be beneficial to have a small map too.  Eventually i would like the undo defense option to undo defences in order they were placed.  OR just click delete on a defense and delete.
